/**
 * Emploments Data
 * Employments Data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateUserDatumDto { 
    title?: string;
    gender?: CreateUserDatumDto.GenderEnum;
    name?: string;
    fname?: string;
    lname?: string;
    genotype?: string;
    bloodGroup?: string;
    maritalStatus?: CreateUserDatumDto.MaritalStatusEnum;
    dateOfBirth?: string;
    placeOfBirth?: string;
    placeOfResidence?: string;
    stateOfResidence?: string;
    lgaOfResidence?: string;
    speakerOfEnglish?: CreateUserDatumDto.SpeakerOfEnglishEnum;
    writingInEnglish?: CreateUserDatumDto.WritingInEnglishEnum;
    levelOfEducation?: CreateUserDatumDto.LevelOfEducationEnum;
    formOfEducation?: CreateUserDatumDto.FormOfEducationEnum;
    skillSet?: string;
    interestHobbies?: string;
    nextOfKinFullName?: string;
    nextOfKinFirstName?: string;
    nextOfKinLastName?: string;
    nextOfKinEmailAddress?: string;
    nextOfKinCurrentAddress?: string;
    nextOfKinStateOfResidence?: string;
    nextOfKinLga?: string;
    about?: string;
    image?: string;
    nextOfKinPhoneNumber?: string;
    emergencyContact?: string;
    address?: string;
    phoneNumber?: string;
    email?: string;
    idealEmployment?: string;
    economicOppurtunitiesAround?: string;
    employedBefore?: string;
    currentlyEmpoyed?: string;
    underEmpoyed?: string;
    userType?: CreateUserDatumDto.UserTypeEnum;
    password?: string;
}
export namespace CreateUserDatumDto {
    export type GenderEnum = 'male' | 'female' | 'other';
    export const GenderEnum = {
        Male: 'male' as GenderEnum,
        Female: 'female' as GenderEnum,
        Other: 'other' as GenderEnum
    };
    export type MaritalStatusEnum = 'married' | 'divorced' | 'seperated' | 'single' | 'widower';
    export const MaritalStatusEnum = {
        Married: 'married' as MaritalStatusEnum,
        Divorced: 'divorced' as MaritalStatusEnum,
        Seperated: 'seperated' as MaritalStatusEnum,
        Single: 'single' as MaritalStatusEnum,
        Widower: 'widower' as MaritalStatusEnum
    };
    export type SpeakerOfEnglishEnum = 'very well' | 'average' | 'not at all';
    export const SpeakerOfEnglishEnum = {
        VeryWell: 'very well' as SpeakerOfEnglishEnum,
        Average: 'average' as SpeakerOfEnglishEnum,
        NotAtAll: 'not at all' as SpeakerOfEnglishEnum
    };
    export type WritingInEnglishEnum = 'very well' | 'average' | 'not at all';
    export const WritingInEnglishEnum = {
        VeryWell: 'very well' as WritingInEnglishEnum,
        Average: 'average' as WritingInEnglishEnum,
        NotAtAll: 'not at all' as WritingInEnglishEnum
    };
    export type LevelOfEducationEnum = 'primary' | 'tertiary' | 'others';
    export const LevelOfEducationEnum = {
        Primary: 'primary' as LevelOfEducationEnum,
        Tertiary: 'tertiary' as LevelOfEducationEnum,
        Others: 'others' as LevelOfEducationEnum
    };
    export type FormOfEducationEnum = 'normadic' | 'arabic' | 'regular';
    export const FormOfEducationEnum = {
        Normadic: 'normadic' as FormOfEducationEnum,
        Arabic: 'arabic' as FormOfEducationEnum,
        Regular: 'regular' as FormOfEducationEnum
    };
    export type UserTypeEnum = 'admin' | 'regular';
    export const UserTypeEnum = {
        Admin: 'admin' as UserTypeEnum,
        Regular: 'regular' as UserTypeEnum
    };
}


