/**
 * Emploments Data
 * Employments Data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateUserDatumDto { 
    title?: string;
    gender?: string;
    name?: string;
    genotype?: string;
    bloodGroup?: string;
    maritalStatus?: string;
    dateOfBirth?: string;
    placeOfBirth?: string;
    placeOfResidence?: string;
    speakerOfEnglish?: boolean;
    writingInEnglish?: boolean;
    levelOfEducation?: string;
    formOfEducation?: string;
    skillSet?: string;
    interestHobbies?: string;
    nextOfKinFullName?: string;
    nextOfKinPhoneNumber?: string;
    emergencyContact?: string;
    address?: string;
    phoneNumber?: string;
    email?: string;
    idealEmployment?: string;
    economicOppurtunitiesAround?: string;
    employedBefore?: boolean;
    currentlyEmpoyed?: boolean;
    underEmpoyed?: boolean;
}

